# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-05 09:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('date_naissance', models.CharField(max_length=255, null=True, verbose_name='date de naissance')),
                ('adresse', models.CharField(max_length=255, verbose_name='adresse postale compl\xe8te')),
                ('email', models.EmailField(max_length=254, verbose_name='adresse email')),
                ('tel', models.CharField(max_length=255, verbose_name='t\xe9l\xe9phone')),
                ('annee_ECN', models.CharField(max_length=255, verbose_name="Ann\xe9e du concours de l'ECN")),
                ('semestre', models.CharField(blank=True, max_length=255, verbose_name='semestre commenc\xe9 en novembre 2016')),
                ('annee_debut_post_internat', models.CharField(help_text='Ann\xe9e, pr\xe9visible ou effective, de d\xe9but de post-internat', max_length=255, verbose_name='ann\xe9e du d\xe9but de post-internat')),
                ('inter_region', models.CharField(choices=[('Ile de France', 'Ile de France'), ('Est', 'Est'), ('Nord', 'Nord'), ('Ouest', 'Ouest'), ('Rh\xf4ne-Alpes', 'Rh\xf4ne-Alpes'), ('Sud', 'Sud'), ('Sud-Ouest', 'Sud-Ouest'), ('DOM-TOM', 'DOM-TOM')], max_length=255, verbose_name='inter-r\xe9gion de formation')),
                ('service_actuel', models.CharField(help_text='Pr\xe9cisez votre centre, le service, le chef de service et la ville', max_length=255, verbose_name='votre service actuel')),
                ('diplome_master_2', models.CharField(choices=[('Non', 'Non'), ('Pas int\xe9ress\xe9', 'Pas int\xe9ress\xe9'), ('En cours', 'En cours'), ('Valid\xe9', 'Valid\xe9')], default='', max_length=255, null=True, verbose_name='Master 2')),
                ('diplome_DESC_andrologie', models.CharField(choices=[('Non', 'Non'), ('Pas int\xe9ress\xe9', 'Pas int\xe9ress\xe9'), ('En cours', 'En cours'), ('Valid\xe9', 'Valid\xe9')], default='', max_length=255, null=True, verbose_name="DESC d'andrologie")),
                ('diplome_DESC_oncologie_1', models.CharField(choices=[('Non', 'Non'), ('Pas int\xe9ress\xe9', 'Pas int\xe9ress\xe9'), ('En cours', 'En cours'), ('Valid\xe9', 'Valid\xe9')], default='', max_length=255, null=True, verbose_name="DESC d'oncologie option m\xe9dicale")),
                ('diplome_DESC_oncologie_2', models.CharField(choices=[('Non', 'Non'), ('Pas int\xe9ress\xe9', 'Pas int\xe9ress\xe9'), ('En cours', 'En cours'), ('Valid\xe9', 'Valid\xe9')], default='', max_length=255, null=True, verbose_name="DESC d'oncologie option chirurgicale")),
                ('diplome_autre', models.TextField(blank=True, default='', help_text='Si oui, pr\xe9cisez.', null=True, verbose_name='Autres diplomes')),
                ('statut_actuel', models.CharField(choices=[('Interne DES', 'Interne DES'), ('Interne titre \xe9tranger', 'Interne titre \xe9tranger'), ('Assistant', 'Assistant'), ('CCA', 'CCA'), ('Autre', 'Autre')], max_length=255, null=True)),
                ('statut_autre', models.CharField(blank=True, help_text="Pr\xe9cisez, si autre statut (m\xe9daille d'or, ann\xe9e de c\xe9sure, mobilit\xe9, ann\xe9e recherche ...)", max_length=255, null=True)),
                ('justificatif_scolarite', models.FileField(help_text='Certificat de scolarit\xe9 (si interne), feuille de paie (si CCA) ou attestation du chef de service', upload_to='uploads/justificatifs/', verbose_name='Pi\xe8ce justificative')),
                ('choix_adhesion', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
